# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fit an AGHQ model via L-BFGS optimization
#' 
#' This function is a C++ implementation of the exact gradient-based optimization
#' of the AGHQ approximate log-marginal likelihood in a binary mixed model.
#' 
#' @param theta Starting value for the outer parameter, containing regression
#' coefficients and variance components on the log-Cholesky scale.
#' @param u Starting value for the inner parameter, representing the mode of the
#' random effects vector.
#' @param y A \code{std::vector} of length \code{m} \code{Eigen} vectors of lengths \code{m_i},
#' containing the responses: one vector of within-group observations per group.
#' @param X A \code{std::vector} of length \code{m} \code{Eigen} matrices of dimensions \code{m_i x p},
#' representing the design matrices for the fixed effects variables.
#' @param Z A \code{std::vector} of length \code{m} \code{Eigen} matrices of dimensions \code{m_i x d},
#' representing the design matrices for the random effects.
#' @param nn An \code{Eigen} matrix of dimension \code{k^d x d} containing the product-rule quadrature nodes.
#' @param ww An \code{Eigen} vector of length \code{k^d} containing the product-rule quadrature weights.
#' @param control a \code{List} containing control arguments.
optimizeaghq <- function(theta, y, X, Z, nn, ww, control) {
    .Call(`_aghqmm_optimizeaghq`, theta, y, X, Z, nn, ww, control)
}

